config/routes.rb
Rails.application.routes.draw do

root to: 'to_dos#index'

get 'tasks' => 'to_dos#index', as: :index

get 'tasks/new' => 'to_dos#new', as: :new
post "tasks", to: "to_dos#create"

get 'tasks/:id' => 'to_dos#show', as: :detail

get 'tasks/:id/edit' => "to_dos#edit", as: :edit
patch 'tasks/:id' => 'to_dos#update'

delete 'tasks/:id' => 'to_dos#destroy', as: :destroy

end

app/models/to_do.rb
class ToDo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController

  def index
    @all = ToDo.all
  end

  def show
    @task = ToDo.find(params[:id])
  end

  def new

  end

  def create
    @task = ToDo.new(task_params)
    @task.save
    redirect_to detail_path(@task)
  end

  def edit
    @task = ToDo.find(params[:id])
  end

  def update
    @task = ToDo.find(params[:id])
    @task.update(task_params)
    @task.save
    redirect_to detail_path(@task)
  end

  def destroy
    @task = ToDo.find(params[:id])
    @task.destroy
    redirect_to index_path
  end


  private

    def task_params
      params.require(:task).permit(:name, :description)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTaskManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/to_dos/create.html.erb
<h1>Created</h1>

app/views/to_dos/edit.html.erb
<h1>Edit</h1>


<form action="/tasks/<%= @task.id  %>" method="post">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <input type="hidden" name="_method" value="patch">
  <input type="text" value= "<%= @task.name %>" name="task[name]">
  <input type="text" value="<%= @task.description %>" name="task[description]">
  <input type="submit">
</form>

app/views/to_dos/index.html.erb
<h1> To Do list</h1>


<p><%= link_to "New Task", new_path %></p>

<ul>

  <% @all.each do |t| %>
    <li>
      <%= t.name %>
      <%= link_to 'Detail', detail_path(t)  %>
    </li>

  <% end %>

</ul>

app/views/to_dos/new.html.erb
<h1>New Task</h1>


<form action="/tasks" method="post">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <input type="text" placeholder="ToDo" name="task[name]">
  <input type="text" placeholder="Description" name="task[description]">
  <input type="submit">
</form>

app/views/to_dos/show.html.erb
<h1>Task: <%= @task.name %></h1>

<p><%= @task.description %></p>

<p><%= link_to "Show all", index_path %></p>
<p><%= link_to "Edit", edit_path %></p>
<p><%= link_to "Delete", destroy_path, method: :delete%></p>

app/views/to_dos/update.html.erb
<h1>Successfully updated</h1>